# Generated by Django 5.0.2 on 2024-02-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='inne',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
