# Generated by Django 5.0.2 on 2024-03-03 15:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypSprawy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_sprawy', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sprawa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('zawieszona', models.BooleanField(default=False)),
                ('zamknieta', models.BooleanField(default=False)),
                ('zgloszona_do_kpp', models.BooleanField(default=False)),
                ('data_rozpoczecia', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_zakonczenia', models.DateTimeField(default=django.utils.timezone.now)),
                ('opis_sprawy', models.TextField(blank=True, max_length=1024, null=True)),
                ('zakres_czynnosci', models.TextField(blank=True, max_length=1024, null=True)),
                ('detektyw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('klient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klient', to=settings.AUTH_USER_MODEL)),
                ('typ_sprawy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sprawy.typsprawy')),
            ],
        ),
    ]
