# Generated by Django 5.0.2 on 2024-03-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprawy', '0002_alter_sprawa_data_zakonczenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprawa',
            name='data_zakonczenia',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
